#!/bin/bash

# Run `git <subcmd>` inside a git repo; otherwise fall back to a local
# ./<subcmd>-all script if present (e.g. ./status-all, ./diff-all, ./show-all, ./push-all).
function _git_smart() {
	local subcmd="$1"; shift
	local local_script="./${subcmd}-all"
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		git "$subcmd" "$@"
	elif [[ -x "$local_script" ]]; then
		"$local_script" "$@"
	elif [[ -e "$local_script" ]]; then
		bash "$local_script" "$@"
	else
		git "$subcmd" "$@"
	fi
}

# trying to load local .gitsa file if any exists
function gitsa() {
	localGITSA="`pwd`/.gitsa"
	# skip self-loop .gitsa re-include
	if [[ "$BASH_SOURCE" != "$localGITSA" ]]; then
	  if [[ -e $localGITSA ]]; then
	      source $localGITSA
	  else
	      echo -e "\e[33mNo local \`.gitsa\` file found!\e[m"
	  fi
	fi

	# promt the success
	echo -e "\e[32mThe Git Shortcut Aliases Are In Effect.\e[m"
}

# Clean up local git branches that no longer exist on remote
function clean-merged-branches() {
  git fetch --prune

  git for-each-ref --format '%(refname:short)' refs/heads/ | while read branch; do
    if ! git show-ref --quiet --verify refs/remotes/origin/$branch; then
      if [ "$branch" != "$(git symbolic-ref --short HEAD)" ]; then
        echo "Deleting local branch: $branch"
        git branch -D "$branch"
      fi
    fi
  done
}


# fixup a commit in the history, add/remove content/file from past commits
# ref: https://stackoverflow.com/a/27721031/1198291
function commit-fixup() {
	git commit --fixup=$1
	git stash
	git rebase --interactive --autosquash $1^
	git stash pop
}
