#!/bin/bash

pushd $HOME &>/dev/null

if [ ! -f .bashrc ]; then
	echo -e "\e[31mThe \`$HOME/.bashrc\` file does not exists!\e[m"
	exit 1
fi

git clone https://github.com/alphamarket/bash_helper-pub.git .bash_helper.d || exit 1

if grep -Fq '. $HOME/.bash_helper.d/bash_helper' $HOME/.bashrc
then
	: # if already included
else
	# if not already included
	echo '
# include bash helpers
if [ -f $HOME/.bash_helper.d/bash_helper ]; then . $HOME/.bash_helper.d/bash_helper; fi' >> .bashrc

curl -so ~/.git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

echo source $HOME/.git-prompt.sh >> $HOME/.bashrc

fi
